- name: catalogue
  hosts: catalogue
  become: yes
  tasks:
    - name: disable the nodejs 10 and enable nodejs 18
      # ansible.builtin.command: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
      ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
    
    - name: Install nodejs
      ansible.builtin.package:
        name: nodejs
        state: present

    - name: Create roboshop user
      ansible.builtin.user:
        name: roboshop

    - name: cretae /app directory
      ansible.builtin.file:
        path: /app 
        state: directory

    - name: download catalogue.zip
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
        dest: /tmp

    - name: extract catalogue.zip
      ansible.builtin.unarchive:
        remote_src: /tmp/catalogue.zip
        dest: /app