- name: catalogue
  hosts: catalogue
  become: yes
  tasks:
    - name: disable the nodejs 10 and enable nodejs 18
      # ansible.builtin.command: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
      ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
    
    - name: Install nodejs
      ansible.builtin.package:
        name: nodejs
        state: present

    - name: Create roboshop user
      ansible.builtin.user:
        name: roboshop

    - name: create /app directory
      ansible.builtin.file:
        path: /app 
        state: directory

    - name: download catalogue.zip
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
        dest: /tmp

    - name: extract catalogue.zip
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes 

    - name: install dependencies
      ansible.builtin.command: npm install 
      args:
        chdir: /app 

    - name: copy the catalogue servcie 
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service

    - name: Daemon reload
      ansible.builtin.systemd_service:
        daemon_reload: true

# Let's start the catalogue after the data is loaded

    - name: Copy mongodb repo
      ansible.builtin.copy:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongodb.repo

    - name: install mongodb client
      ansible.builtin.package:
        name: mongodb-org-shell
        state: present 

    - name: get categories product count
      ansible.builtin.command: mongo --host mongodb.learndevops.space --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
      register: product_count

    - name: Print the Procuct count 
      ansible.builtin.debug:
        msg: "Procuct Count is {{product_count}}"
    
    